// ⚠️  AUTO-GENERATED by @bettercms-ai/codegen v0.2.0 — DO NOT EDIT.
// Live Preview field bindings. Regenerate with: npx @bettercms-ai/codegen --bindings-out <path>
// Spread these onto the elements that render your content; they emit
// data-bcms-field/data-bcms-kind only when the site is built with BCMS_ANNOTATE set.

/**
 * True when this site is built for Live Preview annotation. Set `BCMS_ANNOTATE=1`
 * in the preview build only; unset (the default) ships zero binding attributes.
 * Read defensively so the module is safe in any runtime (browser, Node, edge).
 */
const BCMS_ANNOTATE: boolean = (() => {
  try {
    const v = (globalThis as { process?: { env?: Record<string, string | undefined> } })
      .process?.env?.BCMS_ANNOTATE;
    return v != null && v !== "" && v !== "0" && v !== "false";
  } catch {
    return false;
  }
})();

/**
 * Binding attributes for a CMS-bound element. Spread onto the element that renders a
 * field: `<h1 {...bcmsField("title", "text")}>`. Returns `{}` unless BCMS_ANNOTATE
 * is set, so production markup is untouched.
 */
export function bcmsField(path: string, kind: string): Record<string, string> {
  return BCMS_ANNOTATE ? { "data-bcms-field": path, "data-bcms-kind": kind } : {};
}

/**
 * Field bindings keyed by model slug. Spread a binding onto the element that renders
 * that field. Arrays expose `$(i)` for the item element and one accessor per
 * (one-level) sub-field; primitive arrays expose `value(i)` for the item's scalar.
 */
export const bcms = {
  // (no models defined yet)
} as const;
