// ⚠️  AUTO-GENERATED by @bettercms-ai/codegen v0.2.0 — DO NOT EDIT.
// Regenerate with: npx @bettercms-ai/codegen
// Source of truth: your BetterCMS content models (the same schema the dashboard
// builder and the MCP tools write). Re-run codegen after any schema change.

/**
 * Rich-text field value returned by the Delivery API.
 *
 * - `format`/`value`: the portable, editor-agnostic payload (Lexical EditorState) —
 *   render it with your editor's serializer for full fidelity.
 * - `html`: server-rendered, sanitized HTML (computed render-on-write). Present on
 *   Delivery reads; the simplest path for non-React consumers — safe to inject directly
 *   (e.g. `dangerouslySetInnerHTML`). Optional: legacy/un-normalized values may omit it.
 *
 * The `{ format, value }` contract is unchanged; `html` is additive.
 */
export type RichText = {
  readonly format: string;
  readonly value: unknown;
  readonly html?: string;
};

/**
 * Image / media field value as stored and returned verbatim by the Delivery API
 * (server-normalized on write to the canonical shape). `url` is always present; an
 * unresolved/external value may carry only `url`. `altText` is the accessibility text
 * for `<img alt>`.
 */
export interface BetterCMSImage {
  readonly id?: string;
  readonly url: string;
  readonly name?: string;
  readonly altText?: string | null;
  readonly width?: number;
  readonly height?: number;
}

/**
 * Delivery envelope around a model's typed `data`. `getEntry`/`listEntries` in the
 * Next adapter return this shape, with `fields` typed by the model.
 */
export interface BetterCMSEntry<TFields> {
  readonly slug: string;
  readonly status: "draft" | "published";
  readonly fields: TFields;
  readonly updatedAt: string;
}


/**
 * Registry mapping each model slug to its typed fields. The Next adapter uses this to
 * type `getEntry("blog", ...)` by slug — autocomplete and exhaustiveness for free.
 */
export interface BetterCMSSchema {
  // (no models defined yet)
}

/** Union of all model slugs. */
export type BetterCMSModelSlug = keyof BetterCMSSchema;
